### ISSUE TITLE
Over Eager Rebuilds

### ISSUE THREAD

**Issue by slangley** [okaryo/lazy_load_indexed_stack#1]
When clicking on each tab in sequence (in the example), the tab being clicked on is reloaded (expected), as well as all tabs previously clicked on (unexpected).  This results in potentially expensive build() calls to be run every time you click on a tab.

**Comment by okaryo** [comment]
@slangley 
Thanks for creating the Issue and the PR!

I'll make sure it works here as well and I'll review the code for the PR. Please forgive me if I have to make some minor modifications on my end, such as the style of the code. For example, I may remove debug print.

I have to go to work now, so please wait a bit for me to respond..

**Comment by slangley** [comment]
No worries. No rush. Do what you need to do!  Let me know if you want me to update. 

>

**Comment by okaryo** [comment]
Sorry to keep you waiting.

I reproduced the same problem in my environment. And this is over eager rebuilds as you said.
My knowledge of key and rebuild was poor, so I studied a little.
I will now look at the pull request code you created.

**Comment by okaryo** [comment]
fixed by #2 and #3
